[dev]
command = "npm run dev"
targetPort = 3000
port = 8888

[functions]
  [functions.emails]
  included_files = [
    "./emails/**"
  ]

[build]
command = "npm install --legacy-peer-deps && npm run build"
publish = "dist"

[build.environment]
  NODE_VERSION = "18"

[[headers]]
for = "/api/*"

  [headers.values]
  Cache-Control = "private, no-store, no-cache, max-age=0, must-revalidate"
  Pragma = "no-cache"
  Expires = "0"
  Vary = "Cookie"

[context.production.functions.emails]
included_files = [
  "./emails/**"
]

[context.main.functions.emails]
included_files = [
  "./emails/**"
]
